name: Run Stocks Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"   # כל יום 06:00
    - cron: "0 14 * * *"  # כל יום 14:00

jobs:
  run-stocks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run stocks bot
        run: python stocks_bot.py
        env:
          TOKEN_STOCKS: ${{ secrets.TOKEN_STOCKS }}
          CHAT_ID_STOCKS: ${{ secrets.CHAT_ID_STOCKS }}
